# Config file for automatic testing at travis-ci.org

language: python
python: 3.4
evn:
    global:
        PYTHONUNBUFFERED=yes
before_install:
  - |
    python --version
    uname -a
    lsb_release -a
install:
  - pip install tox
  - pip install coveralls
script:
  - tox -v -- -v
after_success:
  - coveralls
